version: "2"
services:
  db:
    image: postgres:13-alpine
    container_name: my_api_db_1
    restart: always
    ports:
      - "5432:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: app
