version: "2"
services:
  web:
    build: my-app/.
    ports:
      - "5000:5000"
    volumes:
      - ./:/my-app
    container_name: my_app_web_1
    stdin_open: true
    tty: true
    environment:
      ENV_FOR_DYNACONF: development
      PYTHONUNBUFFERED: 1
