"""added user_uid

Revision ID: 4bb79a742c30
Revises: 87b7ca4b36f1
Create Date: 2023-04-26 13:09:08.368465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bb79a742c30'
down_revision = '87b7ca4b36f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_uuid', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['user_uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_uuid')

    # ### end Alembic commands ###
