"""added user roles

Revision ID: 622a48888dca
Revises: 4bb79a742c30
Create Date: 2023-04-26 14:41:17.515356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '622a48888dca'
down_revision = '4bb79a742c30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
