[default]
SECRET_KEY = "you-will-never-guess"
DB_USERNAME = "app_user"
DB_PASSWORD = "app_password"
DATABASE_NAME = "app"

[development]
DB_HOST = "localhost"
SQLALCHEMY_DATABASE_URI = "@jinja postgresql://{{ this.DB_USERNAME }}:{{ this.DB_PASSWORD }}@{{ this.DB_HOST }}:5432/{{ this.DATABASE_NAME }}"

[devcontainer]
DB_HOST = "db" 
SQLALCHEMY_DATABASE_URI = "@jinja postgresql://{{ this.DB_USERNAME }}:{{ this.DB_PASSWORD }}@{{ this.DB_HOST }}:5432/{{ this.DATABASE_NAME }}"

[testing]
TESTING = true
DATABASE_NAME = "test_app"

[staging]

[production]
