[default]
SECRET_KEY = "you-will-never-guess"
DB_USERNAME = "app_user"
DB_PASSWORD = "app_password"
DB_HOST = "localhost"
DATABASE_NAME = "app"
SQLALCHEMY_DATABASE_URI = "@jinja postgresql://{{ this.DB_USERNAME }}:{{ this.DB_PASSWORD }}@{{ this.DB_HOST }}:5432/{{ this.DATABASE_NAME }}"

[development]

[testing]
TESTING = true
DATABASE_NAME = "test_app"

[staging]

[production]
